/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CooperativesDao;
import java.awt.Window;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Cooperatives;

/**
 *
 * @author user
 */
public class coopview extends javax.swing.JFrame {
    private Admin admin;

    public coopview(Admin admin) {
        this.admin=admin;
        initComponents();
        loadCooperativesData();
    }
     public void loadCooperativesData() {
       CooperativesDao cooperativesDao = new CooperativesDao();
        List<Cooperatives> cooperativesList = cooperativesDao.findAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data

        for (Cooperatives coop : cooperativesList) {
            model.addRow(new Object[]{
                coop.getId(),
                coop.getName(),
                coop.getLocation(),
                String.format("%.2f%%", coop.getInterestRate())
            });
        }
    }
     
      private void saveCooperative(Cooperatives existingCoop, String name, String location, String interestStr) {
        CooperativesDao fr=new CooperativesDao();
          
          try {
            double interestRate = Double.parseDouble(interestStr);
            Cooperatives coop = existingCoop != null ? existingCoop : new Cooperatives();
            
            coop.setName(name);
            coop.setLocation(location);
            coop.setInterestRate(interestRate);

            if (existingCoop == null) {
                fr.add(coop);
            } else {
                fr.update(coop);
            }

            loadCooperativesData();
            Window window = SwingUtilities.getWindowAncestor(saveButton);
            if (window != null) {
                window.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for interest rate", 
                "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        dltButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonRefresh = new javax.swing.JButton();
        registerViewBUtton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setText("DELETE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Manage Cooperatives Information");

        homeButton.setBackground(new java.awt.Color(153, 153, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        saveButton.setBackground(new java.awt.Color(0, 0, 0));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("REGISTER ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 109, 41));

        editbutton.setBackground(new java.awt.Color(0, 0, 0));
        editbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editbutton.setForeground(new java.awt.Color(255, 255, 255));
        editbutton.setText("EDIT INFORMATION");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 139, -1, 41));

        dltButton.setBackground(new java.awt.Color(0, 0, 0));
        dltButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dltButton.setForeground(new java.awt.Color(255, 255, 255));
        dltButton.setText("DELETE");
        dltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dltButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 139, 109, 41));

        jTable1.setBackground(new java.awt.Color(153, 255, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CoopID", "Cooperative Name", "Location", "Interest Rate"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, 589, 108));

        ButtonRefresh.setBackground(new java.awt.Color(0, 0, 0));
        ButtonRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonRefresh.setForeground(new java.awt.Color(250, 250, 250));
        ButtonRefresh.setText("REFRESH");
        ButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 109, 41));

        registerViewBUtton.setBackground(new java.awt.Color(0, 0, 0));
        registerViewBUtton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registerViewBUtton.setForeground(new java.awt.Color(255, 255, 255));
        registerViewBUtton.setText("ADD RIDER");
        registerViewBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerViewBUttonActionPerformed(evt);
            }
        });
        getContentPane().add(registerViewBUtton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/javapic.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        jTable1MouseClicked(null);
    }//GEN-LAST:event_editbuttonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    registerformView registerForm = new registerformView(this); // Pass the current coopview instance
    JDialog dialog = new JDialog(this, "Register Cooperative", true); // Modal dialog
    dialog.getContentPane().add(registerForm.getContentPane());
    dialog.pack();
    dialog.setLocationRelativeTo(this); // Center the dialog relative to coopview
    dialog.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void ButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshActionPerformed
      loadCooperativesData();
    }//GEN-LAST:event_ButtonRefreshActionPerformed

    private void dltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltButtonActionPerformed
        // TODO add your handling code here:
   int selectedRow = jTable1.getSelectedRow();
    if (selectedRow >= 0) { // Ensure a row is selected
        // Get the cooperative ID from the selected row
        int coopId = (int) jTable1.getValueAt(selectedRow, 0);
        String coopName = (String) jTable1.getValueAt(selectedRow, 1); // For the confirmation message

        // Show a confirmation dialog
        int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete the cooperative '" + coopName + "'?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirmation == JOptionPane.YES_OPTION) { // User confirmed deletion
            // Delete the cooperative using DAO
            CooperativesDao dao = new CooperativesDao();
            dao.delete(coopId); // Pass the coopId directly

            // Refresh the table
            loadCooperativesData();
            JOptionPane.showMessageDialog(this, "Cooperative deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Selection Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_dltButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow >= 0) { // Ensure a row is selected
        // Get data from the selected row
        int coopId = (int) jTable1.getValueAt(selectedRow, 0);
        String name = (String) jTable1.getValueAt(selectedRow, 1);
        String location = (String) jTable1.getValueAt(selectedRow, 2);
        String interestRateStr = (String) jTable1.getValueAt(selectedRow, 3);
        double interestRate = Double.parseDouble(interestRateStr.replace("%", "")); // Remove the % sign

        // Create a Cooperatives object with the selected data
        Cooperatives selectedCoop = new Cooperatives();
        selectedCoop.setId(coopId);
        selectedCoop.setName(name);
        selectedCoop.setLocation(location);
        selectedCoop.setInterestRate(interestRate);

        // Open the updateview form with the selected cooperative's data
        updateview updateForm = new updateview(this, selectedCoop);
        JDialog dialog = new JDialog(this, "Edit Cooperative", true); // Modal dialog
        dialog.getContentPane().add(updateForm.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this); // Center the dialog
        dialog.setVisible(true); // Show the dialog
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to edit!", "Selection Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void registerViewBUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerViewBUttonActionPerformed
        // TODO add your handling code here:
         new riderView(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerViewBUttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRefresh;
    private javax.swing.JButton dltButton;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton registerViewBUtton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
