/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MotorcyclistDao;
import dao.SavingAccountDao;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.SavingsAccount;

/**
 *
 * @author user
 */
public class SavingsAccView extends javax.swing.JFrame {
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
private Admin admin;
    /**
     * Creates new form SavingsAccView
     */
    public SavingsAccView(Admin admin) {
        this.admin=admin;
        initComponents();
        loadAccountData();
    }
     void loadAccountData() {
    SavingAccountDao accountDao = new SavingAccountDao();
    List<SavingsAccount> accounts = accountDao.getAllAccounts();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing data

    MotorcyclistDao riderDao = new MotorcyclistDao(); // Create DAO instance once
    
    for (SavingsAccount account : accounts) {
        String riderName = riderDao.getRiderName(account.getRiderId());
        
        model.addRow(new Object[]{
            account.getAccountId(),
            account.getAccountNumber(),
            account.getRiderId(),
            account.getBalance(),
            account.getLastInterestDate() != null ? 
                dateFormat.format(account.getLastInterestDate()) : "N/A",
            riderName // Use the actual rider name
        });
    }
}
  private String getRiderName(int riderId) {
    MotorcyclistDao riderDao = new MotorcyclistDao();
    return riderDao.getRiderName(riderId);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        createaccButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        applyInterestButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(195, 195, 195));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdentificationNumber", "AccountNumber", "RiderID", "Balance ", "Last interest Date", "Riders Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 270, 700, 92));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Savings Accounts ");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 748, -1));

        createaccButton.setBackground(new java.awt.Color(0, 0, 0));
        createaccButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createaccButton.setForeground(new java.awt.Color(255, 255, 255));
        createaccButton.setText("Create Account");
        createaccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createaccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 129, -1, 41));

        depositButton.setBackground(new java.awt.Color(0, 0, 0));
        depositButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depositButton.setForeground(new java.awt.Color(255, 255, 255));
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        jPanel1.add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 129, 89, 41));

        applyInterestButton.setBackground(new java.awt.Color(0, 0, 0));
        applyInterestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        applyInterestButton.setForeground(new java.awt.Color(255, 255, 255));
        applyInterestButton.setText("Apply Interest");
        applyInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyInterestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(applyInterestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 129, -1, 41));

        withdrawButton.setBackground(new java.awt.Color(0, 0, 0));
        withdrawButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawButton.setForeground(new java.awt.Color(255, 255, 255));
        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        jPanel1.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 129, 107, 41));

        transferButton.setBackground(new java.awt.Color(0, 0, 0));
        transferButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transferButton.setForeground(new java.awt.Color(255, 255, 255));
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(transferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 131, -1, 39));

        RefreshButton.setBackground(new java.awt.Color(0, 0, 0));
        RefreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh ");
        jPanel1.add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 444, 124, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/javapic.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 740, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
    if (selectedRow >= 0) {
        // Get account info from selected row
        String accountNumber = jTable1.getValueAt(selectedRow, 1).toString();
        String riderName = jTable1.getValueAt(selectedRow, 5).toString();
        
        // Create and show deposit form
        Depositform depositForm = new Depositform(this);
        depositForm.setSelectedAccount(accountNumber, riderName);
        
        JDialog dialog = new JDialog(this, "Deposit to Account", true);
        dialog.getContentPane().add(depositForm.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, 
            "Please select an account first", 
            "No Selection", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void createaccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccButtonActionPerformed
        // TODO add your handling code here:
         CreateAccform createForm = new CreateAccform(this);
    JDialog dialog = new JDialog(this, "Create Savings Account", true);
    dialog.getContentPane().add(createForm.getContentPane());
    dialog.pack();
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    
    // Refresh the table after dialog closes
    loadAccountData();
   
    }//GEN-LAST:event_createaccButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow >= 0) {
        // Get account info from selected row
        String accountNumber = jTable1.getValueAt(selectedRow, 1).toString();
        String riderName = jTable1.getValueAt(selectedRow, 5).toString();
        double currentBalance = (Double)jTable1.getValueAt(selectedRow, 3);
        
        // Create and show withdraw form
        WithdrawForm withdrawForm = new WithdrawForm(this);
        withdrawForm.setSelectedAccount(accountNumber, riderName, currentBalance);
        
        JDialog dialog = new JDialog(this, "Withdraw from Account", true);
        dialog.getContentPane().add(withdrawForm.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, 
            "Please select an account first", 
            "No Selection", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void applyInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyInterestButtonActionPerformed
        // TODO add your handling code here:
         ApplyInterestForm interestForm = new ApplyInterestForm(this);
    JDialog dialog = new JDialog(this, "Apply Monthly Interest", true);
    dialog.getContentPane().add(interestForm.getContentPane());
    dialog.pack();
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_applyInterestButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String accountNumber = jTable1.getValueAt(selectedRow, 1).toString();
            String riderName = jTable1.getValueAt(selectedRow, 5).toString();
            double currentBalance = (Double)jTable1.getValueAt(selectedRow, 3);
            
            TransferForm transferForm = new TransferForm(this);
            transferForm.setSelectedAccount(accountNumber, riderName, currentBalance);
            
            JDialog dialog = new JDialog(this, "Transfer Money", true);
            dialog.getContentPane().add(transferForm.getContentPane());
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            
            loadAccountData(); // Refresh table after transfer
        } else {
            JOptionPane.showMessageDialog(this, 
                "Please select an account first", 
                "No Selection", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_transferButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton applyInterestButton;
    private javax.swing.JButton createaccButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton transferButton;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
