/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.SavingAccountDao;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author user
 */
public class WithdrawForm extends javax.swing.JFrame {
private SavingsAccView parentView;
    private String selectedAccountNumber;
    private String selectedAccountName;
    private double currentBalance;

    /**
     * Creates new form WithdrawForm
     */
    public WithdrawForm(SavingsAccView parent) {
        this.parentView = parent;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Disable withdraw button until account is selected
        WithdrawButton.setEnabled(false);
    }
    
    public void setSelectedAccount(String accountNumber, String accountName, double balance) {
        this.selectedAccountNumber = accountNumber;
        this.selectedAccountName = accountName;
        this.currentBalance = balance;
        
        AccountNumberLabel.setText(accountNumber);
        
        WithdrawButton.setEnabled(true);
        
        // Show current balance
        JOptionPane.showMessageDialog(this, 
            String.format("Current balance: %.2f", balance),
            "Account Balance", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    private String generateReceipt(String accountNumber, String accountName, double amount, double newBalance) {
    StringBuilder receipt = new StringBuilder();
    receipt.append("=== WITHDRAWAL RECEIPT ===\n\n");
    receipt.append(String.format("%-20s: %s\n", "Account Number", accountNumber));
    receipt.append(String.format("%-20s: %s\n", "Account Name", accountName));
    receipt.append(String.format("%-20s: %.2f\n", "Withdrawal Amount", amount));
    receipt.append(String.format("%-20s: %.2f\n", "New Balance", newBalance));
    receipt.append(String.format("%-20s: %s\n", "Date", new java.util.Date()));
    receipt.append("\nThank you for banking with us!");
    return receipt.toString();
}

private void showReceipt(String receipt) {
    JTextArea textArea = new JTextArea(receipt);
    textArea.setEditable(false);
    textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
    
    JScrollPane scrollPane = new JScrollPane(textArea);
    scrollPane.setPreferredSize(new Dimension(400, 300));
    
    JOptionPane.showMessageDialog(this, scrollPane, "Withdrawal Receipt", JOptionPane.INFORMATION_MESSAGE);
    
    // Optional: Add print button functionality
    int print = JOptionPane.showConfirmDialog(this,
        "Would you like to print this receipt?",
        "Print Receipt",
        JOptionPane.YES_NO_OPTION);
    
    if (print == JOptionPane.YES_OPTION) {
        try {
            textArea.print();
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this,
                "Failed to print receipt: " + e.getMessage(),
                "Print Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ammountTxt = new javax.swing.JTextField();
        WithdrawButton = new javax.swing.JButton();
        AccountNumberLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        jPanel2.setBackground(new java.awt.Color(120, 120, 120));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Withdraw from Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ammount");

        ammountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammountTxtActionPerformed(evt);
            }
        });

        WithdrawButton.setText("WITHDRAW");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        AccountNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountNumberLabel.setText("Account Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Account Number:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNumberLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(ammountTxt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNumberLabel)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ammountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addComponent(WithdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ammountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ammountTxtActionPerformed

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
       try {
        // Validate amount
        double amount;
        try {
            amount = Double.parseDouble(ammountTxt.getText().trim());
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "Amount must be greater than zero", 
                    "Invalid Amount", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (amount > currentBalance) {
                JOptionPane.showMessageDialog(this, 
                    String.format("Insufficient balance. Current balance: %.2f", currentBalance),
                    "Insufficient Funds", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a valid amount", 
                "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirm withdrawal
        int confirm = JOptionPane.showConfirmDialog(this, 
            String.format("Withdraw %.2f from account %s?", amount, selectedAccountNumber),
            "Confirm Withdrawal",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Perform withdrawal
        SavingAccountDao accountDao = new SavingAccountDao();
        boolean success = accountDao.withdraw(selectedAccountNumber, amount);
        
        if (success) {
            // Generate receipt
            String receipt = generateReceipt(selectedAccountNumber, selectedAccountName, amount, currentBalance - amount);
            
            // Show success message with receipt option
            int printOption = JOptionPane.showOptionDialog(this,
                "Withdrawal successful!\nWould you like to print a receipt?",
                "Success",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Print Receipt", "Done"},
                "Print Receipt");
            
            if (printOption == JOptionPane.YES_OPTION) {
                showReceipt(receipt);
            }
            
            // Close the form
            this.dispose();
            
            // Refresh parent view
            if (parentView != null) {
                parentView.loadAccountData();
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Withdrawal failed. Please try again.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

     

    }//GEN-LAST:event_WithdrawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JTextField ammountTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
