/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cooperatives;
import service.CooperativesService;

/**
 *
 * @author user
 */
public class CooperativePage1 extends javax.swing.JFrame {
    private CooperativesService service;
    private DefaultTableModel tableModel;

    /**
     * Creates new form CooperativePage1
     */
    public CooperativePage1() {
        initComponents();
        initializeService();
        initializeTable();
        loadCooperatives();
    }
   private void initializeService() {
    try {
        Registry registry = LocateRegistry.getRegistry("127.0.0.1", 2325);
        service = (CooperativesService) registry.lookup("CooperativesService");
        if (service == null) {
            throw new Exception("Failed to lookup CooperativesService");
        }
        System.out.println("Connected to CooperativesService at 127.0.0.1:2325");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cannot connect to server: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Connection failed: " + e.getMessage());
        e.printStackTrace();
        System.exit(1); // Ensure exit
    }
}
 private void initializeTable() {
    tableModel = new DefaultTableModel(new String[]{"ID", "Name", "Location", "Interest Rate"}, 0); // Use class field
    jTable1.setModel(tableModel);
    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
            int row = jTable1.getSelectedRow();
            IDTxt.setText(tableModel.getValueAt(row, 0).toString());
            NameTxt.setText(tableModel.getValueAt(row, 1).toString());
            LocationTxt.setText(tableModel.getValueAt(row, 2).toString());
            InterestRateTxt.setText(tableModel.getValueAt(row, 3).toString());
        }
    });
}
private void loadCooperatives() {
    try {
        if (service == null) {
            JOptionPane.showMessageDialog(this, "Service not initialized. Please restart the application.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tableModel.setRowCount(0); // Clear table
        List<Cooperatives> cooperatives = service.findAll();
        if (cooperatives != null) {
            for (Cooperatives c : cooperatives) {
                if (c != null) { // Avoid null cooperatives
                    tableModel.addRow(new Object[]{
                        c.getId(),
                        c.getName() != null ? c.getName() : "",
                        c.getLocation() != null ? c.getLocation() : "",
                        c.getInterestRate()
                    });
                }
            }
        } else {
            System.out.println("No cooperatives found or service returned null.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading cooperatives: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Load failed: " + ex.getMessage());
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LocationTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InterestRateTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        SearchIdTxt = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SearchByIdButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backIcon.PNG"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 612, Short.MAX_VALUE)
                .addComponent(BackButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(BackButton))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/details Icon.PNG"))); // NOI18N
        jLabel1.setText("Cooperatives Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/updkey.PNG"))); // NOI18N
        jLabel3.setText("ID");

        IDTxt.setEditable(false);
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cooperative Name");

        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Location");

        LocationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Interest Rate");

        InterestRateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterestRateTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDTxt)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTxt)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationTxt)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(InterestRateTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InterestRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/databaseIcon_1.PNG"))); // NOI18N
        jLabel6.setText("Cooperative Database");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Location", "Interest Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/searchIcon.PNG"))); // NOI18N
        jLabel7.setText("Enter Id to Search");

        SearchIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIdTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SearchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        SearchByIdButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchByIdButton.setText("Search");
        SearchByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByIdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(UpdateButton)
                .addGap(107, 107, 107)
                .addComponent(DeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchByIdButton)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(SearchByIdButton))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try {
        if (NameTxt.getText().trim().isEmpty() || LocationTxt.getText().trim().isEmpty() || InterestRateTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double interestRate = Double.parseDouble(InterestRateTxt.getText().trim());
        if (interestRate < 0 || interestRate > 100) {
            JOptionPane.showMessageDialog(this, "Interest rate must be between 0 and 100.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Cooperatives cooperative = new Cooperatives();
        cooperative.setName(NameTxt.getText().trim());
        cooperative.setLocation(LocationTxt.getText().trim());
        cooperative.setInterestRate(interestRate);
        service.save(cooperative);
        JOptionPane.showMessageDialog(this, "Cooperative saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        IDTxt.setText("");
        NameTxt.setText("");
        LocationTxt.setText("");
        InterestRateTxt.setText("");
        SearchIdTxt.setText("");
        loadCooperatives();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid interest rate: Must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Invalid input: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Save failed: " + ex.getMessage());
    }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        try {
        if (IDTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a cooperative to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (NameTxt.getText().trim().isEmpty() || LocationTxt.getText().trim().isEmpty() || InterestRateTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double interestRate = Double.parseDouble(InterestRateTxt.getText().trim());
        if (interestRate < 0 || interestRate > 100) {
            JOptionPane.showMessageDialog(this, "Interest rate must be between 0 and 100.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Cooperatives cooperative = new Cooperatives();
        cooperative.setId(Integer.parseInt(IDTxt.getText().trim()));
        cooperative.setName(NameTxt.getText().trim());
        cooperative.setLocation(LocationTxt.getText().trim());
        cooperative.setInterestRate(interestRate);
        service.update(cooperative);
        JOptionPane.showMessageDialog(this, "Cooperative updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        IDTxt.setText("");
        NameTxt.setText("");
        LocationTxt.setText("");
        InterestRateTxt.setText("");
        SearchIdTxt.setText("");
        loadCooperatives();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input: ID and Interest Rate must be numbers.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Invalid input: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Update failed: " + ex.getMessage());
    }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        try {
        if (IDTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a cooperative to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this cooperative?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(IDTxt.getText().trim());
            Cooperatives cooperative = service.findById(id);
            if (cooperative == null) {
                JOptionPane.showMessageDialog(this, "Cooperative not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            service.delete(cooperative);
            JOptionPane.showMessageDialog(this, "Cooperative deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            IDTxt.setText("");
            NameTxt.setText("");
            LocationTxt.setText("");
            InterestRateTxt.setText("");
            SearchIdTxt.setText("");
            loadCooperatives();
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid ID: Must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Invalid input: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error deleting cooperative: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Delete failed: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SearchByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByIdButtonActionPerformed
        // TODO add your handling code here:
        try {
        String searchId = SearchIdTxt.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter an ID to search.", "Error", JOptionPane.ERROR_MESSAGE);
            loadCooperatives();
            return;
        }
        int id = Integer.parseInt(searchId);
        Cooperatives cooperative = service.findById(id);
        tableModel.setRowCount(0);
        if (cooperative != null) {
            tableModel.addRow(new Object[]{
                cooperative.getId(),
                cooperative.getName() != null ? cooperative.getName() : "",
                cooperative.getLocation() != null ? cooperative.getLocation() : "",
                cooperative.getInterestRate()
            });
        } else {
            JOptionPane.showMessageDialog(this, "No cooperative found with ID " + id, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        SearchIdTxt.setText("");
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid ID: Must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Invalid input: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error searching cooperative: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println("Search failed: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_SearchByIdButtonActionPerformed

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void LocationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationTxtActionPerformed

    private void InterestRateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterestRateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterestRateTxtActionPerformed

    private void SearchIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchIdTxtActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
  new DashBoard1().setVisible(true); // Open SignupFrame
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField InterestRateTxt;
    private javax.swing.JTextField LocationTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchByIdButton;
    private javax.swing.JTextField SearchIdTxt;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
