/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Loan;
import model.Motorcyclist;
import model.SavingsAccount;
import service.LoanService;
import service.SavingsAccountService;

/**
 *
 * @author user
 */
public class LoanPage extends javax.swing.JFrame {
private SavingsAccountService savingsService;
    private LoanService loanService;
    private DefaultTableModel tableModel;
    /**
     * Creates new form NewJFrame
     */
    public LoanPage() {
        initComponents();
        initializeServices();
        initializeTable();
        loadLoans();
        setLocationRelativeTo(null);
    }
        private void initializeServices() {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 2325);
            savingsService = (SavingsAccountService) registry.lookup("SavingsAccountService");
            loanService = (LoanService) registry.lookup("LoanService");
            if (savingsService == null || loanService == null) {
                throw new Exception("Failed to lookup services");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot connect to server: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    private void initializeTable() {
        tableModel = new DefaultTableModel(new Object[]{"Name", "Amount", "Due Date", "Interest Rate", "Status"}, 0);
        jTable1.setModel(tableModel);
    }

    private void loadLoans() {
        try {
            tableModel.setRowCount(0);
            List<Loan> loans = loanService.findAll();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            for (Loan loan : loans) {
                String name = loan.getMotorcyclist() != null ? loan.getMotorcyclist().getName() : "Unknown";
                tableModel.addRow(new Object[]{
                    name,
                    String.format("ZMW %.2f", loan.getAmount()),
                    sdf.format(loan.getDueDate()),
                    String.format("%.2f%%", loan.getInterestRate()),
                    loan.isIsRepaid() ? "Paid" : "Unpaid"
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading loans: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AccNbrTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LoanAmountTxt = new javax.swing.JTextField();
        RequestLoanButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        CheckLoanstutsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backIcon.PNG"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(BackButton))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/request Icon.PNG"))); // NOI18N
        jLabel2.setText("Loan Request ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Account Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Loan Ammount");

        RequestLoanButton.setText("REQUEST LOAN");
        RequestLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestLoanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(AccNbrTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(LoanAmountTxt)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(RequestLoanButton)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccNbrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoanAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RequestLoanButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Names", "amount", "Loan due date", "Interest Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/loan icon.PNG"))); // NOI18N
        jLabel1.setText("Loan Information");

        jLabel5.setText("Enter the account Number to check the loan status");

        CheckLoanstutsButton.setText("Check");
        CheckLoanstutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckLoanstutsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(CheckLoanstutsButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckLoanstutsButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestLoanButtonActionPerformed
        // TODO add your handling code here:
         try {
            String accountNumber = AccNbrTxt.getText().trim();
            String loanAmountStr = LoanAmountTxt.getText().trim();

            if (accountNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Account number is required.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (loanAmountStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Loan amount is required.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double loanAmount;
            try {
                loanAmount = Double.parseDouble(loanAmountStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Loan amount must be a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (loanAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Loan amount must be positive.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SavingsAccount account = null;
            List<SavingsAccount> accounts = savingsService.findAll();
            for (SavingsAccount acc : accounts) {
                if (accountNumber.equals(acc.getAccountNumber())) {
                    account = acc;
                    break;
                }
            }
            if (account == null) {
                JOptionPane.showMessageDialog(this, "Account not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (loanAmount > account.getBalance()) {
                JOptionPane.showMessageDialog(this, "Loan amount cannot exceed current balance.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Motorcyclist motorcyclist = account.getMotorcyclist();
            if (motorcyclist == null) {
                JOptionPane.showMessageDialog(this, "Motorcyclist not associated with account.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<Loan> loans = loanService.findByMotorcyclistId(motorcyclist.getId());
            for (Loan loan : loans) {
                if (!loan.isIsRepaid()) {
                    JOptionPane.showMessageDialog(this, "Cannot request loan: Unpaid loan exists.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Loan loan = new Loan();
            loan.setAmount(loanAmount);
            loan.setInterestRate(5.0); // Fixed 5%
            loan.setIssueDate(new Date());
            Calendar cal = Calendar.getInstance();
            cal.add(Calendar.YEAR, 1);
            loan.setDueDate(cal.getTime());
            loan.setIsRepaid(false);
            loan.setMotorcyclist(motorcyclist);
            loanService.save(loan);

            account.setBalance(account.getBalance() + loanAmount);
            savingsService.update(account);

            JOptionPane.showMessageDialog(this, "Loan of ZMW " + loanAmount + " granted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadLoans();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error requesting loan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RequestLoanButtonActionPerformed

    private void CheckLoanstutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckLoanstutsButtonActionPerformed
        // TODO add your handling code here:
        try {
            String accountNumber = jTextField3.getText().trim();
            if (accountNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Account number is required.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SavingsAccount account = null;
            List<SavingsAccount> accounts = savingsService.findAll();
            for (SavingsAccount acc : accounts) {
                if (accountNumber.equals(acc.getAccountNumber())) {
                    account = acc;
                    break;
                }
            }
            if (account == null) {
                JOptionPane.showMessageDialog(this, "Account not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Motorcyclist motorcyclist = account.getMotorcyclist();
            if (motorcyclist == null) {
                JOptionPane.showMessageDialog(this, "Motorcyclist not associated with account.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<Loan> loans = loanService.findByMotorcyclistId(motorcyclist.getId());
            if (loans.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No loans found for this account.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder status = new StringBuilder("Loan Status for Account: " + accountNumber + "\n\n");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            for (Loan loan : loans) {
                status.append("Loan ID: ").append(loan.getLoanId()).append("\n")
                      .append("Amount: ZMW ").append(String.format("%.2f", loan.getAmount())).append("\n")
                      .append("Issue Date: ").append(sdf.format(loan.getIssueDate())).append("\n")
                      .append("Due Date: ").append(sdf.format(loan.getDueDate())).append("\n")
                      .append("Interest Rate: ").append(String.format("%.2f%%", loan.getInterestRate())).append("\n")
                      .append("Status: ").append(loan.isIsRepaid() ? "Paid" : "Unpaid").append("\n\n");
            }

            JOptionPane.showMessageDialog(this, status.toString(), "Loan Status", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error checking loan status: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CheckLoanstutsButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
          new DashBoard1().setVisible(true); // Open SignupFrame
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNbrTxt;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CheckLoanstutsButton;
    private javax.swing.JTextField LoanAmountTxt;
    private javax.swing.JButton RequestLoanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
